package com.jellyfin.client

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // App/General
    val appVersion: String,
    val detailInfo: String,
    val notAvailable: String,
    
    // Tabs
    val tabHome: String,
    val tabMovies: String,
    val tabTv: String,
    val tabDownload: String,
    val tabSettings: String,

    // Home
    val welcomeTitle: String,
    val welcomeDesc: String,
    val continueWatching: String,
    val latestMovies: String,
    val latestShows: String,
    val emptyServer: String,

    // Movies & TV
    val moviesAZ: String,
    val tvSeriesAZ: String,
    val emptyMovies: String,
    val emptyTv: String,

    // Settings
    val settingsHeader: String,
    val settingsSubtitle: String,
    val groupPlayback: String,
    val groupGeneral: String,
    val layoutSetting: String,
    val layoutMobile: String,
    val layoutMobileDesc: String,
    val layoutTablet: String,
    val layoutTabletDesc: String,
    
    val subtitleSetting: String,
    val subtitleSize: String,
    val sizeSmall: String,
    val sizeNormal: String,
    val sizeLarge: String,
    val subtitleEdge: String,
    val edgeNone: String,
    val edgeOutline: String,
    val edgeShadow: String,

    val appLanguage: String,
    val langIndonesian: String,
    val langEnglish: String,
    val langChinese: String,

    val connectionDetail: String,
    val loginToNexfin: String,
    val serverUrl: String,
    val serverUrlPlaceholder: String,
    val username: String,
    val password: String,
    val loginBtn: String,
    val connectedToServer: String,
    val logoutBtn: String,
    val signOutBtn: String,
    val notConnectedLabel: String,
    val jellyfinServerLabel: String,
    val signedInAs: String,

    // Detail Screens
    val playBtn: String,
    val resumeBtn: String,
    val playFromBeginningBtn: String,
    val synopsis: String,
    val mainCast: String,
    val seeMore: String,
    val synopsisEpisode: String,
    val noSynopsis: String,
    val episodeList: String,
    val noEpisodes: String,

    // Downloads
    val downloadEmptyTitle: String,
    val downloadEmptyDesc: String,
    val downloadStatusDownloading: String,
    val downloadStatusDone: String,
    val downloadStatusError: String,
    val downloadDeleteTitle: String,
    val downloadDeleteMsg: String,   // pakai %s untuk nama item
    val downloadDeleteBtn: String,
    val cancelBtn: String,

    // Continue Watching
    val removeFromContinue: String,
    val removeFromContinueMsg: String  // pakai %s untuk nama item
)

val stringsId = AppStrings(
    appVersion = "Nexfin V.2.0",
    detailInfo = "Detail Info",
    notAvailable = "Belum Tersedia",
    tabHome = "Beranda",
    tabMovies = "Film",
    tabTv = "Shows",
    tabDownload = "Unduhan",
    tabSettings = "Pengaturan",
    welcomeTitle = "Selamat Datang",
    welcomeDesc = "Jelajahi dan putar seluruh koleksi film pribadi Anda langsung melalui server nexfin.",
    continueWatching = "Lanjut Menonton",
    latestMovies = "Film Terbaru",
    latestShows = "Shows Terbaru",
    emptyServer = "Pustaka server nexfin Anda kosong.",
    moviesAZ = "Film",
    tvSeriesAZ = "Shows",
    emptyMovies = "Tidak ada film di server.",
    emptyTv = "Tidak ada serial TV di server.",
    settingsHeader = "Pengaturan",
    settingsSubtitle = "Sesuaikan pengalaman Nexfin Anda",
    groupPlayback = "Pemutaran",
    groupGeneral = "Umum",
    layoutSetting = "Layout",
    layoutMobile = "Mobile (Hanya Portrait)",
    layoutMobileDesc = "Koleksi & menu akan dikunci tegak. Rotasi landscape hanya aktif saat memutar video.",
    layoutTablet = "Tablet (Hanya Landscape)",
    layoutTabletDesc = "Seluruh halaman aplikasi dikunci landscape dengan navigasi sidebar.",
    subtitleSetting = "Subtitle Bawaan",
    subtitleSize = "Ukuran Subtitle",
    sizeSmall = "Kecil",
    sizeNormal = "Normal",
    sizeLarge = "Besar",
    subtitleEdge = "Gaya Tepi (Edge Style)",
    edgeNone = "Tidak Ada",
    edgeOutline = "Garis Luar",
    edgeShadow = "Bayangan",
    appLanguage = "Bahasa Aplikasi",
    langIndonesian = "Indonesia",
    langEnglish = "Inggris",
    langChinese = "Cina",
    connectionDetail = "Jellyfin Connection",
    loginToNexfin = "Login ke Nexfin",
    serverUrl = "Nexfin Server URL",
    serverUrlPlaceholder = "http://192.168.1.100:8096",
    username = "Username",
    password = "Password",
    loginBtn = "Login",
    connectedToServer = "Terhubung ke Server",
    logoutBtn = "Keluar (Logout)",
    signOutBtn = "Keluar",
    notConnectedLabel = "Belum Terhubung",
    jellyfinServerLabel = "Server Jellyfin",
    signedInAs = "Masuk sebagai",
    playBtn = "Putar Film",
    resumeBtn = "Lanjutkan Menonton",
    playFromBeginningBtn = "Putar dari Awal",
    synopsis = "Sinopsis",
    mainCast = "Pemeran Utama",
    seeMore = "Lihat lebih banyak",
    synopsisEpisode = "Sinopsis Episode",
    noSynopsis = "Tidak ada sinopsis untuk episode ini.",
    episodeList = "Daftar Episode",
    noEpisodes = "Tidak ada episode untuk season ini.",
    downloadEmptyTitle = "Belum ada unduhan",
    downloadEmptyDesc = "Unduh film atau episode dari halaman detail\nuntuk menontonnya secara offline.",
    downloadStatusDownloading = "Mengunduh…",
    downloadStatusDone = "✓ Tersimpan offline",
    downloadStatusError = "⚠ Gagal — ketuk untuk coba lagi",
    downloadDeleteTitle = "Hapus Unduhan",
    downloadDeleteMsg = "Hapus \"%s\" dari penyimpanan perangkat?",
    downloadDeleteBtn = "Hapus",
    cancelBtn = "Batal",
    removeFromContinue = "Hapus dari Lanjut Menonton",
    removeFromContinueMsg = "Hapus \"%s\" dari daftar lanjut menonton?"
)

val stringsEn = AppStrings(
    appVersion = "Nexfin V.2.0",
    detailInfo = "Detail Info",
    notAvailable = "Not Available",
    tabHome = "Home",
    tabMovies = "Movies",
    tabTv = "Shows",
    tabDownload = "Downloads",
    tabSettings = "Settings",
    welcomeTitle = "Welcome",
    welcomeDesc = "Explore and play your entire personal movie collection directly through the nexfin server.",
    continueWatching = "Continue Watching",
    latestMovies = "Latest Movies",
    latestShows = "Latest Shows",
    emptyServer = "Your nexfin server library is empty.",
    moviesAZ = "Movies",
    tvSeriesAZ = "Shows",
    emptyMovies = "No movies on the server.",
    emptyTv = "No TV shows on the server.",
    settingsHeader = "Settings",
    settingsSubtitle = "Customize your Nexfin experience",
    groupPlayback = "Playback",
    groupGeneral = "General",
    layoutSetting = "Layout",
    layoutMobile = "Mobile (Portrait Only)",
    layoutMobileDesc = "Collections & menus will be locked to portrait. Landscape rotation is only active during video playback.",
    layoutTablet = "Tablet (Landscape Only)",
    layoutTabletDesc = "The entire application is locked to landscape with a sidebar navigation.",
    subtitleSetting = "Default Subtitle",
    subtitleSize = "Subtitle Size",
    sizeSmall = "Small",
    sizeNormal = "Normal",
    sizeLarge = "Large",
    subtitleEdge = "Edge Style",
    edgeNone = "None",
    edgeOutline = "Outline",
    edgeShadow = "Drop Shadow",
    appLanguage = "App Language",
    langIndonesian = "Indonesian",
    langEnglish = "English",
    langChinese = "Chinese",
    connectionDetail = "Jellyfin Connection",
    loginToNexfin = "Login to Nexfin",
    serverUrl = "Nexfin Server URL",
    serverUrlPlaceholder = "http://192.168.1.100:8096",
    username = "Username",
    password = "Password",
    loginBtn = "Login",
    connectedToServer = "Connected to Server",
    logoutBtn = "Log Out",
    signOutBtn = "Sign out",
    notConnectedLabel = "Not Connected",
    jellyfinServerLabel = "Jellyfin Server",
    signedInAs = "Signed in as",
    playBtn = "Play Movie",
    resumeBtn = "Resume Watching",
    playFromBeginningBtn = "Play from Beginning",
    synopsis = "Synopsis",
    mainCast = "Main Cast",
    seeMore = "See more",
    synopsisEpisode = "Episode Synopsis",
    noSynopsis = "No synopsis available for this episode.",
    episodeList = "Episode List",
    noEpisodes = "No episodes available for this season.",
    downloadEmptyTitle = "No downloads yet",
    downloadEmptyDesc = "Download movies or episodes from the detail screen\nto watch them offline.",
    downloadStatusDownloading = "Downloading…",
    downloadStatusDone = "✓ Saved offline",
    downloadStatusError = "⚠ Failed — tap to retry",
    downloadDeleteTitle = "Delete Download",
    downloadDeleteMsg = "Delete \"%s\" from device storage?",
    downloadDeleteBtn = "Delete",
    cancelBtn = "Cancel",
    removeFromContinue = "Remove from Continue Watching",
    removeFromContinueMsg = "Remove \"%s\" from your watchlist?"
)

val stringsZh = AppStrings(
    appVersion = "Nexfin V.2.0",
    detailInfo = "详细信息",
    notAvailable = "暂不可用",
    tabHome = "首页",
    tabMovies = "电影",
    tabTv = "Shows",
    tabDownload = "下载",
    tabSettings = "设置",
    welcomeTitle = "欢迎",
    welcomeDesc = "通过 nexfin 服务器直接探索并播放您的整个个人电影收藏。",
    continueWatching = "继续观看",
    latestMovies = "最新电影",
    latestShows = "最新节目",
    emptyServer = "您的 nexfin 服务器库为空。",
    moviesAZ = "电影",
    tvSeriesAZ = "Shows",
    emptyMovies = "服务器上没有电影。",
    emptyTv = "服务器上没有电视节目。",
    settingsHeader = "设置",
    settingsSubtitle = "自定义您的 Nexfin 体验",
    groupPlayback = "播放",
    groupGeneral = "通用",
    layoutSetting = "布局",
    layoutMobile = "手机（仅限竖屏）",
    layoutMobileDesc = "收藏和菜单将锁定为竖屏。横屏旋转仅在视频播放时处于活动状态。",
    layoutTablet = "平板（仅限横屏）",
    layoutTabletDesc = "整个应用程序锁定为横屏，并带有侧边栏导航。",
    subtitleSetting = "默认字幕",
    subtitleSize = "字幕大小",
    sizeSmall = "小",
    sizeNormal = "正常",
    sizeLarge = "大",
    subtitleEdge = "边缘样式",
    edgeNone = "无",
    edgeOutline = "轮廓",
    edgeShadow = "阴影",
    appLanguage = "应用语言",
    langIndonesian = "印尼语",
    langEnglish = "英语",
    langChinese = "中文",
    connectionDetail = "Jellyfin Connection",
    loginToNexfin = "登录 Nexfin",
    serverUrl = "Nexfin 服务器 URL",
    serverUrlPlaceholder = "http://192.168.1.100:8096",
    username = "用户名",
    password = "密码",
    loginBtn = "登录",
    connectedToServer = "已连接到服务器",
    logoutBtn = "退出登录",
    signOutBtn = "退出",
    notConnectedLabel = "未连接",
    jellyfinServerLabel = "Jellyfin 服务器",
    signedInAs = "登录为",
    playBtn = "播放电影",
    resumeBtn = "继续观看",
    playFromBeginningBtn = "从头开始播放",
    synopsis = "剧情简介",
    mainCast = "主要演员",
    seeMore = "查看更多",
    synopsisEpisode = "分集简介",
    noSynopsis = "该集暂无简介。",
    episodeList = "剧集列表",
    noEpisodes = "该季暂无剧集。",
    downloadEmptyTitle = "暂无下载",
    downloadEmptyDesc = "从详情页面下载电影或剧集\n以便离线观看。",
    downloadStatusDownloading = "下载中…",
    downloadStatusDone = "✓ 已离线保存",
    downloadStatusError = "⚠ 下载失败 — 点击重试",
    downloadDeleteTitle = "删除下载",
    downloadDeleteMsg = "从设备存储中删除\"%s\"？",
    downloadDeleteBtn = "删除",
    cancelBtn = "取消",
    removeFromContinue = "从继续观看中移除",
    removeFromContinueMsg = "从继续观看列表中移除\"%s\"？"
)

val LocalAppStrings = staticCompositionLocalOf<AppStrings> { 
    error("No AppStrings provided") 
}
